### ISSUE TITLE
Size transition not working

### ISSUE THREAD

**Issue by fabien** [appleple/ui-expand#1]
Hi, 

This looks really interesting! However, I can't seem to get it to work with non-pixel based (or non-fixed) sized items.

Before expanding (in the event for it) I measure the current width/height and set those explicitly as pixel values temporarily. This works when opening.

However, when closing the item, it jumps abruptly back into place, without transitioning the size. In order to make this work properly, I guess it would be helpful if a placeholder item would be placed on opening, so this placeholder can be used to query the current dimensions to resize back to when closing.

Just some thoughts ...

**Comment by steelydylan** [comment]
@fabien I think your idea to place placeholders is nice
I'll improve the code!
thank you :)

**Comment by steelydylan** [comment]
Hi @fabien I just fixed the library as you told me
plz start the project if you like ;)

**Comment by fabien** [comment]
Thanks @steelydylan it works perfectly now! Only thing I keep doing in the beforeOpen handler is set a higher z-index for the element. This was necessary in my case at least.
